export const CAR_BRANDS = [
  // Classic/Vintage Brands
  "Morris",
  "Austin",
  "Hillman",
  "Vauxhall",
  "Opel",
  "Saab",
  "Lancia",
  "Alfa Romeo",
  "Fiat",
  "Peugeot",
  "Renault",
  "Citroën",
  "Škoda",
  "Wartburg",
  "Lada",
  "Yugo",

  // Japanese Brands (Old to New)
  "Toyota",
  "Nissan",
  "Honda",
  "Mazda",
  "Mitsubishi",
  "Subaru",
  "Suzuki",
  "Daihatsu",
  "Isuzu",
  "Hino",
  "UD Trucks",
  "Lexus",
  "Infiniti",
  "Acura",

  // American Brands
  "Ford",
  "Chevrolet",
  "Chrysler",
  "Dodge",
  "Plymouth",
  "Pontiac",
  "Oldsmobile",
  "Buick",
  "Cadillac",
  "Lincoln",
  "Mercury",
  "GMC",
  "Jeep",
  "Hummer",
  "Saturn",
  "Eagle",
  "Geo",
  "Scion",
  "Tesla",

  // German Brands
  "Volkswagen",
  "BMW",
  "Mercedes-Benz",
  "Audi",
  "Porsche",
  "Maybach",
  "Smart",
  "Mini",

  // Korean Brands
  "Hyundai",
  "KIA",
  "Daewoo",
  "SsangYong",
  "Genesis",

  // European Brands
  "Volvo",
  "Jaguar",
  "Land Rover",
  "Rolls-Royce",
  "Bentley",
  "Aston Martin",
  "Lotus",
  "McLaren",
  "Ferrari",
  "Lamborghini",
  "Maserati",
  "Bugatti",

  // Chinese Brands
  "Chery",
  "Geely",
  "BYD",
  "Great Wall",
  "Haval",
  "JAC",
  "SAIC",
  "Dongfeng",
  "FAW",
  "Changan",
  "BAIC",
  "Brilliance",
  "Foton",
  "Lifan",
  "Zotye",
  "MG",
  "Lynk & Co",
  "Polestar",
  "NIO",
  "Xpeng",
  "Li Auto",
  "Zeekr",
  "Ora",

  // Malaysian Brands
  "Proton",
  "Perodua",

  // Indian Brands
  "Tata",
  "Mahindra",
  "Maruti Suzuki",
  "Bajaj",
  "Force Motors",
  "Ashok Leyland",

  // Other Brands
  "Holden",
  "Seat",
  "Dacia",
  "Mitsuoka",
  "Spyker",
  "Koenigsegg",
  "Pagani",
];

export const CAR_TYPES_BY_BRAND: { [key: string]: string[] } = {
  // Classic/Vintage Brands
  Morris: ["Minor", "Oxford", "Marina", "Ital"],
  Austin: [
    "Mini",
    "A30",
    "A35",
    "A40",
    "A50",
    "A55",
    "A60",
    "A99",
    "A110",
    "Maxi",
    "Allegro",
    "Princess",
    "Ambassador",
    "Montego",
    "Maestro",
  ],
  Hillman: ["Minx", "Hunter", "Imp", "Avenger", "Gazelle"],
  Vauxhall: [
    "Victor",
    "Viva",
    "Chevette",
    "Cavalier",
    "Astra",
    "Vectra",
    "Omega",
    "Corsa",
    "Nova",
  ],
  Opel: [
    "Kadett",
    "Ascona",
    "Rekord",
    "Manta",
    "GT",
    "Admiral",
    "Diplomat",
    "Omega",
    "Vectra",
    "Astra",
    "Corsa",
    "Insignia",
  ],
  Saab: ["92", "93", "95", "96", "99", "900", "9000", "9-3", "9-5", "9-7X"],
  Lancia: [
    "Fulvia",
    "Beta",
    "Gamma",
    "Delta",
    "Thema",
    "Dedra",
    "Kappa",
    "Lybra",
    "Musa",
    "Ypsilon",
  ],
  "Alfa Romeo": [
    "Giulia",
    "Giulietta",
    "Alfetta",
    "GTV",
    "Spider",
    "75",
    "90",
    "155",
    "156",
    "159",
    "166",
    "147",
    "GT",
    "Brera",
    "MiTo",
    "Stelvio",
    "Tonale",
  ],
  Fiat: [
    "500",
    "600",
    "126",
    "127",
    "128",
    "131",
    "132",
    "Panda",
    "Uno",
    "Tipo",
    "Tempra",
    "Croma",
    "Punto",
    "Bravo",
    "Brava",
    "Marea",
    "Multipla",
    "Stilo",
    "Idea",
    "Grande Punto",
    "Linea",
    "500X",
    "500L",
    "Panda Cross",
    "Argo",
    "Cronos",
    "Toro",
    "Mobi",
    "Strada",
  ],
  Peugeot: [
    "204",
    "304",
    "404",
    "504",
    "505",
    "604",
    "104",
    "204",
    "304",
    "305",
    "309",
    "405",
    "406",
    "407",
    "408",
    "508",
    "605",
    "607",
    "807",
    "1007",
    "2008",
    "3008",
    "5008",
    "Partner",
    "Expert",
    "Boxer",
    "Rifter",
    "Traveller",
  ],
  Renault: [
    "4CV",
    "Dauphine",
    "8",
    "10",
    "12",
    "16",
    "18",
    "20",
    "21",
    "25",
    "Clio",
    "Megane",
    "Laguna",
    "Vel Satis",
    "Espace",
    "Scenic",
    "Modus",
    "Twingo",
    "Captur",
    "Kadjar",
    "Koleos",
    "Talisman",
    "Arkana",
    "Austral",
  ],
  Citroën: [
    "2CV",
    "Ami",
    "Dyane",
    "Mehari",
    "GS",
    "GSA",
    "CX",
    "BX",
    "XM",
    "Xantia",
    "Xsara",
    "C3",
    "C4",
    "C5",
    "C6",
    "C1",
    "C2",
    "C3 Aircross",
    "C4 Cactus",
    "C5 Aircross",
    "Berlingo",
    "Picasso",
    "SpaceTourer",
  ],
  Škoda: [
    "1000MB",
    "105",
    "120",
    "130",
    "Favorit",
    "Felicia",
    "Octavia",
    "Fabia",
    "Superb",
    "Roomster",
    "Yeti",
    "Rapid",
    "Citigo",
    "Kodiaq",
    "Karoq",
    "Scala",
    "Kamiq",
    "Enyaq",
  ],
  Wartburg: ["311", "312", "353", "1.3"],
  Lada: [
    "1200",
    "1300",
    "1500",
    "1600",
    "Niva",
    "Samara",
    "Riva",
    "110",
    "111",
    "112",
    "Kalina",
    "Priora",
    "Granta",
    "Largus",
    "Vesta",
    "XRAY",
  ],
  Yugo: ["45", "55", "65", "Koral", "Florida", "Tempo", "Cabrio"],

  // Toyota - From Old to New Models
  Toyota: [
    // Classic Models (1960s-1980s)
    "Corona",
    "Crown",
    "Carina",
    "Celica",
    "Supra",
    "Starlet",
    "Tercios",
    "Corolla (KE20/30)",
    "Hiace (H10/20)",
    "Land Cruiser (FJ40/55)",
    "Hilux (RN10/20/30)",
    // 1980s-1990s Models
    "Camry (XV10)",
    "Previa",
    "Corolla (AE80/90)",
    "Tercios (AL10)",
    "Kijang (KF10/20/40)",
    "Corolla Twincam",
    "Corona Absolute",
    "Cressida",
    "MR2",
    "Celica (ST162/185)",
    "Supra (A70/80)",
    // 1990s-2000s Models
    "Corolla (AE100/110)",
    "Camry (XV20/30)",
    "Vitz",
    "Platz",
    "Soluna",
    "Kijang (KF50/70/80)",
    "Kijang Innova (TGN40)",
    "Avanza (F600)",
    "RAV4 (XA10/20)",
    "Prado (J90/120)",
    "Fortuner (GGN50)",
    // 2000s-2010s Models
    "Yaris",
    "Vios",
    "Corolla Altis",
    "Camry (XV40/50)",
    "Alphard (ANH10/20)",
    "Vellfire",
    "Sienta",
    "Calya",
    "Agya",
    "Rush",
    "C-HR",
    "Innova Zenix",
    // Current/Latest Models
    "Raize",
    "Corolla Cross",
    "Hilux Revo",
    "Fortuner (AN160)",
    "Land Cruiser (300 Series)",
    "Prius",
    "Camry Hybrid",
    "Alphard (AH30)",
    "Vellfire (AGH30)",
    "Hiace (H300)",
    "Dyna (XZU/TRY)",
    "Coaster",
  ],

  // Honda - From Old to New Models
  Honda: [
    // Classic Models
    "Civic (SB1/2)",
    "Accord (SY/SZ)",
    "Prelude",
    "CRX",
    "Civic Wonder (SB3/4)",
    "Civic Nova (SR3/4)",
    "Civic Genio (EG)",
    "Civic Estilo (EG)",
    "Accord Maestro (CB)",
    "Civic Ferio (EK)",
    // 1990s-2000s Models
    "City (SX8)",
    "Jazz (GD)",
    "Civic VTi (EK9)",
    "Accord VTi (CG)",
    "CR-V (RD1/2)",
    "Stream (RN1)",
    "Freed (GB3/4)",
    "City (GM2/3)",
    "Jazz (GE8)",
    "Civic (FD/FB)",
    "Accord (CL7/9, CP1/2/3)",
    // Current Models
    "Brio",
    "Mobilio",
    "BR-V",
    "HR-V",
    "CR-V (RW)",
    "Pilot",
    "Jazz (GK5)",
    "City (GM6)",
    "Civic (FC/FK)",
    "Accord (CV3)",
    "Freed (GB5/6/7/8)",
    "Odyssey",
    "Ridgeline",
    "Civic Type R",
    "NSX",
    "Passport",
    "Insight",
  ],

  // Nissan - From Old to New Models
  Nissan: [
    // Classic Models
    "Datsun 1000",
    "Datsun 1200",
    "Datsun 120Y",
    "Datsun 140J",
    "Datsun 160J",
    "Datsun 180B",
    "Datsun 200L",
    "Datsun 240Z",
    "Datsun 260Z",
    "Datsun 280Z",
    "Skyline (C10/C110)",
    "Cedric",
    "Gloria",
    // 1980s-1990s Models
    "Sunny (B11/12/13)",
    "Sentra (B13/14)",
    "Altima (U13)",
    "Maxima (J30)",
    "Cefiro (A31/32)",
    "Skyline (R31/32/33/34)",
    "Silvia (S13/14/15)",
    "180SX",
    "200SX",
    "240SX",
    "300ZX",
    "Pathfinder (WD21)",
    "Terrano (D21)",
    // 2000s Models
    "March (K11/12)",
    "Almera (N15/16)",
    "Primera (P10/11/12)",
    "Teana (J31/32)",
    "X-Trail (T30/31)",
    "Murano (Z50/51)",
    "Grand Livina",
    "Livina",
    "Latio",
    "Evalia",
    // Current Models
    "March (K13)",
    "Almera (N18)",
    "Kicks",
    "X-Trail (T32/33)",
    "Terra",
    "Navara (D23)",
    "GT-R (R35)",
    "Leaf",
    "Serena (C27)",
    "Elgrand (E52)",
    "Juke (F15/16)",
    "Magnite",
    "Ariya",
    "Z (RZ34)",
    "Patrol",
    "Armada",
  ],

  // Mitsubishi - From Old to New Models
  Mitsubishi: [
    // Classic Models
    "Galant (A50/60/70)",
    "Lancer (A70/90)",
    "Colt (A150/160)",
    "Minica",
    "Delica (L300)",
    "Pajero (L040/140)",
    "Starion",
    "Eclipse (1G/2G)",
    "3000GT/GTO",
    "Diamante",
    // 1990s-2000s Models
    "Lancer EVO (I-X)",
    "Galant (E50/60/70)",
    "Colt (Z20/30)",
    "Carisma",
    "Space Star",
    "Grandis",
    "Outlander (CU2W/CW)",
    "Pajero Sport (K90)",
    "L200/Strada (K60/70)",
    "Canter",
    // Current Models
    "Mirage",
    "Attrage",
    "Xpander",
    "Outlander (GF/GG)",
    "Outlander Sport/ASX",
    "Pajero Sport (KS/KT)",
    "Triton (KL/KR)",
    "Eclipse Cross",
    "Montero",
    "Fuso",
    "eK Space",
    "eK Cross",
    "Delica D:5",
    "i-MiEV",
  ],

  // Mazda - From Old to New Models
  Mazda: [
    // Classic Models
    "R100",
    "RX-2",
    "RX-3",
    "RX-4",
    "RX-7 (SA/FB/FC/FD)",
    "808",
    "818",
    "323 (FA4)",
    "626 (CB/GC/GD/GE/GF/GW)",
    "929",
    "B-Series",
    "E-Series",
    // 1990s-2000s Models
    "Familia (BG/BH/BJ)",
    "Capella (CG/GF/GW)",
    "Millenia",
    "MPV (LV/LW)",
    "Demio (DW/DY)",
    "Premacy (CP/CW)",
    "Tribute (EP)",
    "RX-8",
    "Atenza/Mazda6 (GG/GH/GJ/GL)",
    "Axela/Mazda3 (BK/BL/BM/BN/BP)",
    // Current Models
    "Mazda2 (DE/DJ/DL)",
    "Mazda3 (BP/BT)",
    "Mazda6 (GJ/GL)",
    "CX-3",
    "CX-5 (KE/KF)",
    "CX-9 (TB/TC)",
    "CX-30",
    "CX-50",
    "CX-60",
    "CX-70",
    "CX-90",
    "MX-5 (NA/NB/NC/ND)",
    "MX-30",
    "BT-50",
    "Biante",
  ],

  // Suzuki - From Old to New Models
  Suzuki: [
    // Classic Models
    "Fronte",
    "Cervo",
    "Alto (SS30/40)",
    "Swift (SA310)",
    "Cultus",
    "Baleno (EG)",
    "Esteem",
    "Sidekick",
    "Samurai",
    "Vitara (ET/TA)",
    "Grand Vitara (FT/GT/JT)",
    "X-90",
    "Carry (ST30/40/90)",
    "Every",
    // 1990s-2000s Models
    "Karimun",
    "APV",
    "Futura",
    "Jimny (JA11/12/22)",
    "Swift (HT51S)",
    "SX4 (GY/EY)",
    "Splash",
    "Wagon R (CT/CV)",
    "A-Star",
    "Kizashi",
    // Current Models
    "Celerio",
    "Swift (ZC/ZD)",
    "Baleno (EW)",
    "Ciaz",
    "Ertiga",
    "XL7",
    "Jimny (JB74)",
    "S-Cross",
    "Vitara (LY)",
    "Grand Vitara (LY)",
    "Carry Pro",
    "New Carry",
    "Ignis",
    "S-Presso",
    "Fronx",
    "Invicto",
  ],

  // Daihatsu - From Old to New Models
  Daihatsu: [
    // Classic Models
    "Charade (G10/11/100)",
    "Cuore/Mira (L60/70/80)",
    "Applause",
    "Feroza",
    "Rocky",
    "Hijet (S40/80/100)",
    "Delta",
    "Zebra",
    "Classy",
    "Espass",
    // 1990s-2000s Models
    "Ceria",
    "Taruna",
    "Terios (J100/200)",
    "Xenia (M80)",
    "Sirion (M100/300)",
    "Gran Max",
    "Luxio",
    // Current Models
    "Ayla",
    "Sigra",
    "Xenia (M800)",
    "Terios (F800)",
    "Hi-Max",
    "Copen",
    "Move",
    "Tanto",
    "Cast",
    "Wake",
    "Thor",
    "Taft",
    "Rocky (A200)",
    "Raize",
  ],

  // Isuzu - From Old to New Models
  Isuzu: [
    // Classic Models
    "Gemini",
    "Florian",
    "Bellett",
    "Trooper (UBS)",
    "Amigo",
    "Rodeo",
    "Pickup (TF)",
    "Panther (TBR)",
    "Elf (NHR/NKR)",
    "Giga (CXZ)",
    "Hi-Lander",
    // Current Models
    "D-Max (TF/RT)",
    "MU-X (UC)",
    "Traga",
    "Elf (NLR/NMR/NPR/NQR)",
    "Giga (CYZ/EXZ/FVZ)",
    "GALA",
    "Journey",
  ],

  // Hyundai - From Old to New Models
  Hyundai: [
    // Classic Models
    "Pony",
    "Stellar",
    "Excel",
    "Elantra (J1/J2)",
    "Sonata (Y2/Y3)",
    "Scoupe",
    "Accent (X3/LC/MC/RB/HCR)",
    "Tiburon",
    "Santa Fe (SM/CM)",
    "Tucson (JM)",
    "Matrix/Lavita",
    "Getz (TB)",
    "Atoz/Atos",
    // Current Models
    "i10",
    "i20",
    "Accent",
    "Elantra (CN7)",
    "Sonata (DN8)",
    "Azera/Grandeur",
    "Genesis",
    "Tucson (NX4)",
    "Santa Fe (TM)",
    "Palisade",
    "Creta",
    "Venue",
    "Kona",
    "Ioniq",
    "Ioniq 5",
    "Ioniq 6",
    "Nexo",
    "H-1/Starex",
    "Porter",
    "Mighty",
  ],

  // KIA - From Old to New Models
  KIA: [
    // Classic Models
    "Pride",
    "Sephia",
    "Avella",
    "Clarus",
    "Credos",
    "Sportage (NB-7)",
    "Carens (FC)",
    "Rio (DC/JB)",
    "Cerato (LD)",
    "Magentis/Optima (MS/MG)",
    "Sorento (BL)",
    "Carnival/Sedona (GQ)",
    // Current Models
    "Picanto (TA)",
    "Rio (YB/FB)",
    "Cerato/Forte (BD/CD)",
    "Optima/K5 (JF/DL3)",
    "Stinger",
    "Sportage (QL/NQ5)",
    "Sorento (UM/MQ4)",
    "Telluride",
    "Seltos",
    "Sonet",
    "Stonic",
    "Niro",
    "Soul",
    "Carnival (KA4)",
    "EV6",
    "EV9",
    "Mohave/Borrego",
  ],

  // Ford - From Old to New Models
  Ford: [
    // Classic Models
    "Cortina",
    "Escort (Mk1-6)",
    "Capri",
    "Granada",
    "Sierra",
    "Orion",
    "Fiesta (Mk1-3)",
    "Mondeo (Mk1)",
    "Galaxy (Mk1)",
    "Ka (Mk1)",
    "Puma",
    "Courier",
    "Bronco (1G-5G)",
    "F-Series (F1-F150)",
    "Mustang (1G-4G)",
    "Thunderbird",
    // 1990s-2000s Models
    "Focus (1G/2G)",
    "Fiesta (Mk4-6)",
    "Mondeo (Mk2/3)",
    "C-MAX",
    "S-MAX",
    "Galaxy (Mk2)",
    "Ka (Mk2)",
    "Fusion",
    "Kuga (1G)",
    "Explorer (1G-4G)",
    "Expedition (1G-3G)",
    "F-150 (10G-12G)",
    "Ranger (1G-3G)",
    "Mustang (5G)",
    "Crown Victoria",
    "Taurus",
    // Current Models
    "Fiesta (Mk7/8)",
    "Focus (3G/4G)",
    "Mondeo (Mk4/5)",
    "EcoSport",
    "Kuga/Escape (2G/3G)",
    "Edge",
    "Explorer (5G/6G)",
    "Expedition (4G)",
    "F-150 (13G/14G)",
    "Super Duty",
    "Ranger (4G)",
    "Maverick",
    "Bronco (6G)",
    "Bronco Sport",
    "Mustang (6G)",
    "Mustang Mach-E",
    "Transit",
    "E-Series",
    "Everest",
  ],

  // Chevrolet - From Old to New Models
  Chevrolet: [
    // Classic Models
    "Corvair",
    "Camaro (1G-4G)",
    "Chevelle",
    "Nova",
    "Impala (1G-9G)",
    "Corvette (C1-C6)",
    "El Camino",
    "Monte Carlo",
    "Chevette",
    "Citation",
    "Cavalier",
    "Beretta",
    "Corsica",
    "Lumina",
    "Caprice",
    // 1990s-2000s Models
    "Geo Metro",
    "Geo Prizm",
    "Geo Tracker",
    "Blazer (S-10)",
    "S-10",
    "Silverado (GMT800/900)",
    "Suburban (GMT800/900)",
    "Tahoe (GMT800/900)",
    "Avalanche",
    "Colorado",
    "Malibu (1G-3G)",
    "Cobalt",
    "HHR",
    "Aveo (T200/250)",
    "Spark (M200/300)",
    // Current Models
    "Spark (M400)",
    "Sonic",
    "Cruze",
    "Malibu (4G)",
    "Impala (10G)",
    "Camaro (6G)",
    "Corvette (C7/C8)",
    "Trax",
    "Equinox",
    "Traverse",
    "Blazer",
    "Tahoe (GMT T1XX)",
    "Suburban (GMT T1XX)",
    "Silverado (GMT T1XX)",
    "Colorado (GMT 31XX)",
    "Bolt EV",
    "Bolt EUV",
  ],

  // Volkswagen - From Old to New Models
  Volkswagen: [
    // Classic Models
    "Beetle/Bug (Type 1)",
    "Type 2 (Bus/Microbus)",
    "Type 3",
    "Type 4",
    "K70",
    "Passat (B1/B2)",
    "Golf (Mk1/2)",
    "Polo (Mk1/2)",
    "Scirocco (Mk1/2)",
    "Jetta (Mk1/2)",
    "Corrado",
    "Cabriolet",
    // 1990s-2000s Models
    "Golf (Mk3/4/5)",
    "Polo (Mk3/4)",
    "Passat (B3/B4/B5/B6)",
    "Jetta (Mk3/4/5)",
    "New Beetle",
    "Lupo",
    "Fox",
    "Bora",
    "Sharan",
    "Touran",
    "Touareg (7L)",
    "Phaeton",
    // Current Models
    "Up!",
    "Polo (Mk5/6)",
    "Golf (Mk6/7/8)",
    "Jetta (Mk6/7)",
    "Passat (B7/B8/B9)",
    "Arteon",
    "Beetle (A5)",
    "Tiguan (5N/AD1)",
    "Touareg (7P/CR)",
    "Atlas",
    "ID.3",
    "ID.4",
    "ID.5",
    "ID.Buzz",
    "Amarok",
    "Crafter",
    "Caddy",
    "Transporter T6/T7",
  ],

  // BMW - From Old to New Models
  BMW: [
    // Classic Models
    "1500",
    "1600",
    "1800",
    "2000",
    "2002",
    "3.0 CS",
    "3.0 CSL",
    "E3 (2500/2800/3.0/3.3)",
    "E9 (2800 CS/3.0 CS/3.0 CSL)",
    "E12 (5 Series)",
    "E21 (3 Series)",
    "E23 (7 Series)",
    "E24 (6 Series)",
    "E28 (5 Series)",
    "E30 (3 Series)",
    "E32 (7 Series)",
    "E34 (5 Series)",
    // 1990s-2000s Models
    "E36 (3 Series)",
    "E38 (7 Series)",
    "E39 (5 Series)",
    "E46 (3 Series)",
    "E53 (X5)",
    "E60/E61 (5 Series)",
    "E63/E64 (6 Series)",
    "E65/E66 (7 Series)",
    "E70 (X5)",
    "E83 (X3)",
    "E85/E86 (Z4)",
    "E87/E81/E82/E88 (1 Series)",
    "E90/E91/E92/E93 (3 Series)",
    "R50/R52/R53 (MINI)",
    "R55/R56/R57/R58/R59/R60/R61 (MINI)",
    // Current Models
    "F20/F21 (1 Series)",
    "F22/F23 (2 Series)",
    "F30/F31/F34/F35 (3 Series)",
    "F32/F33/F36 (4 Series)",
    "F10/F11/F07 (5 Series)",
    "F12/F13/F06 (6 Series)",
    "F01/F02/F03/F04 (7 Series)",
    "G11/G12 (7 Series)",
    "G20/G21 (3 Series)",
    "G22/G23/G26 (4 Series)",
    "G30/G31 (5 Series)",
    "G32 (6 Series GT)",
    "G14/G15/G16 (8 Series)",
    "E84 (X1)",
    "F48 (X1)",
    "F25 (X3)",
    "G01 (X3)",
    "F26 (X4)",
    "G02 (X4)",
    "F15 (X5)",
    "G05 (X5)",
    "F16 (X6)",
    "G06 (X6)",
    "G07 (X7)",
    "F89 (Z4)",
    "i3",
    "i4",
    "iX",
    "iX3",
  ],

  // Mercedes-Benz - From Old to New Models
  "Mercedes-Benz": [
    // Classic Models
    "W108/W109 (S-Class)",
    "W110/W111/W112",
    "W113 (SL)",
    "W114/W115",
    "W116 (S-Class)",
    "W123 (E-Class)",
    "W124 (E-Class)",
    "W126 (S-Class)",
    "W129 (SL)",
    "W140 (S-Class)",
    "W201 (190)",
    "W202 (C-Class)",
    "R129 (SL)",
    // 1990s-2000s Models
    "W203 (C-Class)",
    "W210 (E-Class)",
    "W220 (S-Class)",
    "W163 (M-Class)",
    "W168 (A-Class)",
    "W169 (A-Class)",
    "W171 (SLK)",
    "W204 (C-Class)",
    "W211 (E-Class)",
    "W221 (S-Class)",
    "W164 (M-Class)",
    "W251 (R-Class)",
    "C117 (CLA)",
    "C218 (CLS)",
    "X204 (GLK)",
    // Current Models
    "W176/W177 (A-Class)",
    "W246/W247 (B-Class)",
    "W205/W206 (C-Class)",
    "C117/C118 (CLA)",
    "C218/C257 (CLS)",
    "W212/W213 (E-Class)",
    "W222/W223 (S-Class)",
    "X156/H247 (GLA)",
    "X247 (GLB)",
    "X253/X254 (GLC)",
    "X166/X167 (GLE)",
    "X164/X166/X167 (GL/GLS)",
    "W463 (G-Class)",
    "R172/R231 (SL)",
    "R171/R172 (SLK/SLC)",
    "C190 (AMG GT)",
    "EQA",
    "EQB",
    "EQC",
    "EQE",
    "EQS",
    "EQV",
  ],

  // Audi - From Old to New Models
  Audi: [
    // Classic Models
    "60/70/80/90 (F103)",
    "100 (C1/C2/C3)",
    "200",
    "Quattro",
    "80 (B2/B3/B4)",
    "90 (B2/B3)",
    "100 (C4)",
    "A6 (C4)",
    "A4 (B5)",
    "A8 (D2)",
    "TT (8N)",
    "A3 (8L)",
    "A2",
    // 2000s Models
    "A4 (B6/B7)",
    "A6 (C5/C6)",
    "A8 (D3)",
    "TT (8J)",
    "A3 (8P)",
    "Q7 (4L)",
    "R8 (42)",
    "A5 (8T)",
    "Q5 (8R)",
    "A1 (8X)",
    "A7 (4G)",
    // Current Models
    "A1 (GB)",
    "A3 (8V/8Y)",
    "A4 (B8/B9)",
    "A5 (8T/F5)",
    "A6 (C7/C8)",
    "A7 (4G/4K)",
    "A8 (D4/D5)",
    "Q2 (GA)",
    "Q3 (8U/F3)",
    "Q4 e-tron",
    "Q5 (FY)",
    "Q7 (4M)",
    "Q8 (4M)",
    "TT (8S)",
    "R8 (4S)",
    "e-tron",
    "e-tron GT",
    "RS e-tron GT",
  ],

  // Subaru - From Old to New Models
  Subaru: [
    // Classic Models
    "360",
    "1000",
    "Leone",
    "BRAT",
    "XT",
    "Loyale",
    "Justy",
    "Legacy (1G)",
    "SVX",
    "Impreza (1G)",
    "Forester (1G)",
    "Legacy (2G)",
    "Impreza (2G)",
    // 2000s Models
    "Legacy (3G/4G)",
    "Impreza (2.5G/3G)",
    "Forester (2G/3G)",
    "Outback (2G/3G)",
    "Baja",
    "B9 Tribeca",
    "WRX",
    "WRX STI",
    // Current Models
    "Impreza (4G/5G)",
    "Legacy (5G/6G/7G)",
    "Outback (4G/5G/6G)",
    "Forester (4G/5G)",
    "XV/Crosstrek",
    "Ascent",
    "WRX (VA/VB)",
    "WRX STI",
    "BRZ",
    "Solterra",
  ],

  // Lexus - From Old to New Models
  Lexus: [
    // Classic Models
    "LS (XF10/XF20)",
    "ES (XV10/XV20)",
    "SC (Z30)",
    "GS (S140/S160)",
    "IS (XE10)",
    "RX (XU10)",
    "LX (FZJ80)",
    "GX (UZJ100)",
    // 2000s Models
    "LS (XF30/XF40)",
    "ES (XV30/XV40)",
    "SC (Z40)",
    "GS (S190/S190)",
    "IS (XE20)",
    "RX (XU30/AL10)",
    "LX (UZJ200)",
    "GX (UZJ120)",
    "CT (ZWA10)",
    "HS (ANF10)",
    // Current Models
    "LS (XF50)",
    "ES (XV60/XV70)",
    "IS (XE30/XE40)",
    "GS (L10)",
    "RC (SC10)",
    "LC (URZ100)",
    "UX (MZAA10)",
    "NX (AZ10/AZ20)",
    "RX (AL20/AL25)",
    "GX (J150/J460)",
    "LX (URJ200/VDJ200)",
    "LFA",
    "UX 300e",
    "RZ",
  ],

  // Tesla - From Old to New Models
  Tesla: [
    "Roadster (1G)",
    "Model S",
    "Model X",
    "Model 3",
    "Model Y",
    "Cybertruck",
    "Roadster (2G)",
    "Semi",
  ],

  // Chinese Brands
  BYD: [
    // Early Models
    "F0",
    "F3",
    "F3R",
    "F6",
    "G3",
    "G6",
    "L3",
    "M6",
    "S6",
    "S7",
    "S8",
    "e6",
    // Current Models
    "Yuan",
    "Song",
    "Tang",
    "Qin",
    "Han",
    "Seal",
    "Dolphin",
    "Atto 3",
    "Blade Battery series",
    "Dynasty series",
    "Ocean series",
  ],

  Geely: [
    "CK",
    "MK",
    "FC",
    "GC2",
    "GC5",
    "GC6",
    "GC7",
    "GC9",
    "GX2",
    "GX7",
    "LC",
    "SC7",
    "Vision",
    "Emgrand",
    "Boyue",
    "Binyue",
    "Xingyue",
    "Jiaji",
    "Atlas",
    "Coolray",
    "Azkarra",
    "Okavango",
    "Tugella",
  ],

  Chery: [
    "QQ",
    "A1",
    "A3",
    "A5",
    "E3",
    "E5",
    "Fulwin",
    "Tiggo 3",
    "Tiggo 5",
    "Tiggo 7",
    "Tiggo 8",
    "Arrizo 3",
    "Arrizo 5",
    "Arrizo 6",
    "Arrizo 7",
    "Omoda 5",
    "Tiggo 4 Pro",
    "Tiggo 7 Pro",
    "Tiggo 8 Pro",
  ],

  "Great Wall": [
    "Hover",
    "Voleex",
    "Wingle",
    "Haval H1",
    "Haval H2",
    "Haval H6",
    "Haval H7",
    "Haval H8",
    "Haval H9",
    "Haval F5",
    "Haval F7",
    "WEY VV5",
    "WEY VV6",
    "WEY VV7",
    "Ora Good Cat",
    "Tank 300",
    "Tank 500",
  ],

  MG: [
    // Classic Models
    "MG3",
    "MG5",
    "MG6",
    "MG7",
    "MG350",
    "MG550",
    "MG750",
    // Current Models
    "MG3 (2G)",
    "MG5 (2G)",
    "MG6 (2G)",
    "ZS",
    "HS",
    "RX5",
    "RX8",
    "Marvel R",
    "EHS",
    "ZS EV",
    "EP",
    "Cyberster",
    "MG4 Electric",
  ],

  // Malaysian Brands
  Proton: [
    "Saga",
    "Wira",
    "Satria",
    "Perdana",
    "Waja",
    "Gen-2",
    "Savvy",
    "Persona",
    "Exora",
    "Inspira",
    "Preve",
    "Suprima S",
    "Iriz",
    "Ertiga",
    "Persona (2G)",
    "X50",
    "X70",
    "S70",
    "X90",
  ],

  Perodua: [
    "Kancil",
    "Rusa",
    "Kembara",
    "Kelisa",
    "Kenari",
    "Myvi",
    "Viva",
    "Alza",
    "Axia",
    "Bezza",
    "Aruz",
    "Ativa",
    "Myvi (3G)",
  ],

  // Other Classic/Vintage Brands
  Holden: [
    "FX",
    "FJ",
    "FE",
    "FC",
    "FB",
    "EK",
    "EJ",
    "EH",
    "HD",
    "HR",
    "HK",
    "HT",
    "HG",
    "HQ",
    "HJ",
    "HX",
    "HZ",
    "WB",
    "VB",
    "VC",
    "VH",
    "VK",
    "VL",
    "VN",
    "VP",
    "VR",
    "VS",
    "VT",
    "VX",
    "VY",
    "VZ",
    "VE",
    "VF",
    "Commodore",
    "Calais",
    "Statesman",
    "Caprice",
    "Ute",
    "Cruze",
    "Barina",
    "Astra",
    "Vectra",
    "Berlina",
    "SS",
    "HSV",
  ],

  Seat: [
    "600",
    "850",
    "124",
    "127",
    "131",
    "132",
    "Panda",
    "Ronda",
    "Malaga",
    "Marbella",
    "Toledo",
    "Ibiza",
    "Cordoba",
    "Arosa",
    "Leon",
    "Altea",
    "Alhambra",
    "Exeo",
    "Mii",
    "Ateca",
    "Arona",
    "Tarraco",
    "Formentor",
    "Born",
  ],

  Dacia: [
    "1300",
    "1310",
    "Nova",
    "Solenza",
    "Logan",
    "Sandero",
    "Duster",
    "Lodgy",
    "Dokker",
    "Spring",
    "Jogger",
  ],

  // Luxury/Exotic Brands
  Ferrari: [
    "250",
    "275",
    "330",
    "365",
    "308",
    "328",
    "348",
    "355",
    "360",
    "430",
    "458",
    "488",
    "F8",
    "SF90",
    "Roma",
    "Portofino",
    "GTC4Lusso",
    "812",
    "LaFerrari",
    "F40",
    "F50",
    "Enzo",
    "Testarossa",
    "512",
    "Mondial",
    "California",
    "FF",
    "F12",
    "F599",
    "F575",
    "F550",
    "F456",
  ],

  Lamborghini: [
    "350GT",
    "400GT",
    "Miura",
    "Espada",
    "Islero",
    "Jarama",
    "Urraco",
    "Silhouette",
    "Jalpa",
    "Countach",
    "Diablo",
    "Murciélago",
    "Gallardo",
    "Aventador",
    "Huracán",
    "Urus",
    "Revuelto",
    "Sterrato",
  ],

  Porsche: [
    "356",
    "911 (1G-8G)",
    "912",
    "914",
    "924",
    "928",
    "944",
    "968",
    "Boxster",
    "Cayman",
    "Cayenne",
    "Macan",
    "Panamera",
    "Taycan",
    "918 Spyder",
    "Carrera GT",
  ],

  "Rolls-Royce": [
    "Silver Cloud",
    "Silver Shadow",
    "Silver Spirit",
    "Silver Spur",
    "Corniche",
    "Camargue",
    "Silver Seraph",
    "Park Ward",
    "Phantom",
    "Ghost",
    "Wraith",
    "Dawn",
    "Cullinan",
    "Spectre",
  ],

  Bentley: [
    "S1",
    "S2",
    "S3",
    "T1",
    "T2",
    "Corniche",
    "Mulsanne",
    "Turbo R",
    "Brooklands",
    "Azure",
    "Arnage",
    "Continental GT",
    "Continental Flying Spur",
    "Bentayga",
    "Flying Spur",
  ],

  Jaguar: [
    "XK120",
    "XK140",
    "XK150",
    "Mark VII",
    "Mark VIII",
    "Mark IX",
    "Mark X",
    "S-Type (1G)",
    "E-Type",
    "XJ (1G-4G)",
    "XJS",
    "XK8",
    "XKR",
    "S-Type (2G)",
    "X-Type",
    "XF",
    "XE",
    "F-Type",
    "F-Pace",
    "E-Pace",
    "I-Pace",
  ],

  "Land Rover": [
    "Series I",
    "Series II",
    "Series III",
    "Defender",
    "Range Rover (1G-5G)",
    "Discovery (1G-5G)",
    "Freelander",
    "Range Rover Sport",
    "Range Rover Evoque",
    "Range Rover Velar",
    "Defender (L663)",
  ],

  "Aston Martin": [
    "DB2",
    "DB3",
    "DB4",
    "DB5",
    "DB6",
    "DBS",
    "V8",
    "Lagonda",
    "Virage",
    "DB7",
    "DB9",
    "V8 Vantage",
    "DBS (2G)",
    "Rapide",
    "One-77",
    "Virage (2G)",
    "Vanquish",
    "DB11",
    "Vantage (2G)",
    "DBS Superleggera",
    "DBX",
  ],

  // Electric/New Energy Brands
  NIO: ["ES8", "ES6", "EC6", "ET7", "ET5", "ES7", "EC7", "ET9"],

  Xpeng: ["G3", "P7", "P5", "G6", "G9", "X9"],

  "Li Auto": ["Li ONE", "Li L9", "Li L8", "Li L7", "Li L6"],

  Polestar: [
    "Polestar 1",
    "Polestar 2",
    "Polestar 3",
    "Polestar 4",
    "Polestar 5",
  ],

  Zeekr: ["001", "009", "X", "007"],

  Ora: ["R1", "iQ", "Good Cat", "Ballet Cat", "Lightning Cat", "Punk Cat"],
};
